server:
  port: 8080
  context-path: /


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf8
    username: root
    password: lh445566

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: false

  profiles:
    active: @profileActive@

# Swagger界面内容配置
swagger:
  title: 用户认证中心API接口文档
  description: 用户认证中心API接口文档
  version: 1.0.0
  termsOfServiceUrl: https://www.sscai.club
  contact:
    name: 万达信息
    url: https://www.wondersgroup.club
    email: wonders@wondersgroup.com